### ISSUE TITLE
Cors issue

### ISSUE THREAD

**Issue by linusblom** [chas-academy/09-recipe-book-joakimunge#2]
I'm running in to some CORS issue when trying to signup.
![cors](https://user-images.githubusercontent.com/22654895/37140048-a0da54a0-22b0-11e8-964c-284ad4c26c1e.jpeg)

**Comment by joakimunge** [comment]
Strange. I have CORS set up in the backend and running every request through a cors-proxy.. I'll look into it asap.

**Comment by joakimunge** [comment]
@linusblom In the meantime, you can use this account for further testing:

test@test.se // testing

**Comment by linusblom** [comment]
The thing is that I tried to signup with test@test.se and then I ran in to the CORS issue. Trying with a diffrent e-mail it works great. So my bad, never mind, I close this one.

**Comment by joakimunge** [comment]
Ah I see! I should probably respond with a real error message if user exists.. 

Great to hear at least!
